// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDN9Fxyim4Lgt8AWEZTV_P3kjF8DssGXI4',
    appId: '1:424354169530:web:fa8bdc1f5da8ad30753883',
    messagingSenderId: '424354169530',
    projectId: 'kagojkolom',
    authDomain: 'kagojkolom.firebaseapp.com',
    storageBucket: 'kagojkolom.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBh_ef3Dt3baN8px-wrliqfdqrxniUwgOA',
    appId: '1:424354169530:android:2a4e6666f64f094a753883',
    messagingSenderId: '424354169530',
    projectId: 'kagojkolom',
    storageBucket: 'kagojkolom.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcmRHvcDwzTfz2EIj8H26u27DMGrlOS-0',
    appId: '1:424354169530:ios:70e33f09b66b9828753883',
    messagingSenderId: '424354169530',
    projectId: 'kagojkolom',
    storageBucket: 'kagojkolom.firebasestorage.app',
    iosBundleId: 'com.example.kagojkolom',
  );
}
